### ISSUE TITLE
Script cannot obtain latest Drupal version

### ISSUE THREAD

**Issue by Sanchiz** [cibox/cibox#581] opened 2017-06-26 08:57 UTC
When you generate new project, Ansible script cannot obrain Drupal version from XML.

**Comment by ddrozdik** [comment] 2017-06-26 09:07
this happens only on Mac Os X

**Comment by ddrozdik** [comment] 2017-06-26 16:23
actually, I have already reported this issue here https://github.com/cibox/cibox/issues/563

**Comment by podarok** [comment] 2017-06-27 10:16
Duplicate of https://github.com/cibox/cibox/issues/563

**Closed by podarok** 2017-06-27 10:16 UTC
Labels: bug
